### ISSUE TITLE
肉鸽卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [Lancarus/Liver-Arknights-Tomorrow#2]
肉鸽会在遇到安全的角落卡住，软件在尝试几次之后会直接放弃本次作战（当然我自己也尝试点开节点辅助这个软件，但是没用，还是卡住）

**Comment by Lancarus** [comment]
请问一下用的什么设置,是尽量往前推的模式么,可能是之前没有碰到过所以没有识别

**Comment by xiaoweiXX** [comment]
是尽量往前推

**Comment by Lancarus** [comment]
新版本尝试修复了一下，虽然还是有的时候不识别但是应该不会卡住了
