### ISSUE TITLE
any way to translate the app? or can I help translate to English?

### ISSUE THREAD

**Issue by skzidan** [Lancarus/Liver-Arknights-Tomorrow#21]

**Comment by Lancarus** [comment]
Thanks, but there is no need to translate the app.I will not update the app anymore. If you want an app to play arknights automatically, I suggest [Maa](https://github.com/MistEO/MeoAssistantArknights) or [速通](https://github.com/tkkcc/ArkLights)

**Comment by 227675454** [comment]
en ui or use on en server？

**Comment by skzidan** [comment]
> en ui or use on en server？

Use on EN server with en UI
