### ISSUE TITLE
肉鸽不上新干员

### ISSUE THREAD

**Issue by xiaoweiXX** [Lancarus/Liver-Arknights-Tomorrow#3]
肉鸽在进入第二场及以后的战斗中不会加入新招募的干员。不加入的原因并非当前阵容已经足够，漏怪漏的很多，甚至连既有的医疗干员也不会上（虽然在没上的那张图确实用不到医疗）

**Comment by Lancarus** [comment]
这个做的时候就只是尝试用初始三个队员看看能往前推进多少,所以没有做其他干员的识别编队和部署,如果想尽量往前推可以试试 [maa](https://github.com/MistEO/MeoAssistantArknights)

**Comment by xiaoweiXX** [comment]
这个肉鸽做的智能度不太够，经常干员放的很怪，我向作者反馈过这个问题，作者就向我推荐了这个项目。实测放干员的方法确实智能了很多，而且如果我手动把招募到的干员选上似乎也能正常使用这些干员。
![IMG_20220130_012916](https://user-images.githubusercontent.com/92417243/151671098-ef9cc16e-e9af-493b-82a7-35f641686830.jpg)
