### ISSUE TITLE
刷开局时遇到特殊藏品停止

### ISSUE THREAD

**Issue by UVJkiNTQ** [Lancarus/Liver-Arknights-Tomorrow#6]
看到界面上有三个商品的占位符，有更新的计划吗？

另外，模拟器同时存在官服和B服时，能不能给个选项选定。默认好像只会启动官服。

**Comment by Lancarus** [comment]
工作有点忙,暂时不打算更新了,有需求可以看看[maa](https://github.com/MaaAssistantArknights/MaaAssistantArknights)和[速通](https://github.com/tkkcc/ArkLights)

**Comment by UVJkiNTQ** [comment]
感谢回复，另外俩个也有再看
