### ISSUE TITLE
跪求大佬帮我改本地的作业编辑器

### ISSUE THREAD

**Issue by Lancarus** [Lancarus/Liver-Arknights-Tomorrow#7]
需求：
1.希望能把json字符串存成.txt格式
2.群组能加一个字段么{“qty_reqd”:数字},群组中需要的数量,方便在不定干员的作业里编队使用
3.另外能修一下群组里面干员的上下移动和删除按钮就好了，现在这三个按钮都没反应

**Comment by Lancarus** [comment]
爆炸了，发现作业行数多了上下移动真的要人命

**Comment by Shawnsdaddy** [comment]
> 爆炸了，发现作业行数多了上下移动真的要人命

对啊，原来我写的是拖动，非要改成上下移动

**Comment by Lancarus** [comment]
感谢
